#include <iostream.h>
#include <conio.h>
#include <stdio.h>
#include <string.h>
#include <graphics.h>
#include <dos.h>
#include <iomanip.h>
#include "LINE.CPP"
#include "WC.CPP"
#include "CRADITS.CPP"
#include "LIST.CPP"

static int dtotal=0;
static int d[6]={0};

#include "FILE.CPP"
#include "MMCHECK.CPP"
#include "MCHECK.CPP"
#include "MMLIST.CPP"
#include "MLIST.CPP"
#include "COUNT.CPP"
#include "STATUS.CPP"
#include "MENU.CPP"