void list(void)
{
gotoxy(50,9);
	cout<<"Disease List:";
gotoxy(50,10);
	cout<<"1.Fever";
gotoxy(50,11);
	cout<<"2.Cold Virus";
gotoxy(50,12);
	cout<<"3.Yellow Fever";
gotoxy(50,13);
	cout<<"4.Cholera";
gotoxy(50,14);
	cout<<"5.Diphtheria";
}

void clist(void)
{
gotoxy(50,9);
	space(25);
gotoxy(50,10);
	space(25);
gotoxy(50,11);
	space(25);
gotoxy(50,12);
	space(25);
gotoxy(50,13);
	space(25);
gotoxy(50,14);
	space(25);
}